---
title: "Drone Testing & Registration"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  # pdf_document: default
  # html_document:
  #   df_print: paged
  rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


# FAA & UF Rules & Regulations 

1. Overview of FAA Requirements: [Certificated Remote Pilots including Commercial Operators](https://www.faa.gov/uas/commercial_operators/)  
2. UF EH&S UAS [Proceedures and Rules](https://www.ehs.ufl.edu/programs/uas/uf/)


# Proposed  Plan

1. Obtain FTN [link](https://iacra.faa.gov/IACRA/Default.aspx)
2. Read IACRA [Users Guide](https://iacra.faa.gov/IACRA/HelpAndInfo.aspx?id=5)
3. Register for the [Exam](https://faa.psiexams.com/faa/login)
4. Download

    * FAA Remote Pilot – Small Unmanned Aircraft Systems Study Guide [pdf](https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/media/remote_pilot_study_guide.pdf)
    * FAA Aeronautical Information Manaual (AIM) [pdf](https://www.faa.gov/air_traffic/publications/media/aim_basic_dtd_10-12-17.pdf)
    * FAA Pilot’s Handbook of Aeronautical Knowledge [html](https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/phak/) or [pdf](https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/phak/media/pilot_handbook.pdf)

5. Buy

    * FAA Airman Knowledge Testing Supplement - Sport Pilot, Recreational Pilot, and Private Pilot [(available at Amazon, ~$10)](https://www.amazon.com/ASA-Airman-Knowledge-Testing-Supplement/dp/B01K0L2WOA). It is used for the exam so you are given one then, but worth buying in advance so you can study with the actually book/questions used in the exam.

5. Plan a study schedule based on exam date. Some resources include...

    * UF LinkedIn Learning [Video Course](https://www.linkedin.com/learning/cert-prep-faa-107-commercial-drone-license/eligibility-and-test-locations?u=41282748)

    * TMac overview on studying for the exam (kinda annoying but lots of really useful info): [YouTube](https://www.youtube.com/watch?v=s4R3WEQgHoo). Includes link to his [study Notes](https://drive.google.com/file/d/1K_wvpc1Flhx3c4HPJU0p4OtpRYJInEHF/view) and lots of other resources in the video notes

## Other Exam Prep Materials  

  * FAA [Training Resources](https://www.faa.gov/training_testing/training/)  
      
  * Information on tests, number of questions, and passing scores [FAA pdf](https://www.faa.gov/training_testing/testing/media/testing_matrix.pdf)  
    
  * UF LinkedIn Learning Online Certification [Video Course #2](https://www.linkedin.com/learning/cert-prep-faa-part-107-commercial-drone-license-2017/the-test?u=41282748)  
      
  * FAA [Practice Exams](https://faa.psiexams.com/FAA/login)  
      
  * [DPGS](https://www.dronepilotgroundschool.com/missed-part-107-test-prep-questions/) Test Prep Questions  
  
  
# Study Schedule for Exam May 3-7, 2021

## Week 1

* UF LinkedIn Learning Course [Section 1 - Taking the test](https://www.linkedin.com/learning/cert-prep-faa-107-commercial-drone-license/what-does-the-test-cover?u=41282748)
* Tony Northrup Video (free drone cert. guide)
* Airspace  

    
    * UF LinkedIn Learning Course [Section 2 - National Airspace](https://www.linkedin.com/learning/cert-prep-faa-107-commercial-drone-license/what-does-the-test-cover?u=41282748)
    * Pilot's Handbook of Aero Knowledge: 15.1-15.11
    * Remote Pilot UAS Study Guide: Ch 2, pp 5-14
    * Aero Info Manual Ch 3, 3.1.1 - 3.4.2

* Sectional Charts  

    
    * Aero Charts users guide pp. 1-19, 23-30
    * Pilot's Handbook of Aero Knowledge: 16.1-16.11
    * Remote Pilot UAS Study Guide: Ch 1, pp 67-70
    * Video - Aeroworks Productions, Sectional Charts Parts 1-3    

## Week 2


* UF LinkedIn Learning Course [Section 3 - ATC](https://www.linkedin.com/learning/cert-prep-faa-107-commercial-drone-license/what-does-the-test-cover?u=41282748)

* Airport Ops


    * Pilot's Handbook of Aero Knowledge: 14.20-14.26
    * Remote Pilot UAS Study Guide: Ch 1, pp 65-67
    * Aero Info Manual Ch 4, 4.1.1 - 4.1.10
    * Aero Info Manual Ch 4, 4.2.5
    * Aero Info Manual Ch 4, 4.3.1-4.3.5
    

* Weather and WX Reports


    * UF LinkedIn Learning Course [Section 4 - Aviation Weather](https://www.linkedin.com/learning/cert-prep-faa-107-commercial-drone-license/what-does-the-test-cover?u=41282748)
    * Pilot's Handbook of Aero Knowledge: 13.5-13.12
    * Remote Pilot UAS Study Guide: Ch 3, pp 15-28
    * Remote Pilot UAS Study Guide: Ch. 8 p. 48


## Week 3

* Small UAS Loading


    * UF LinkedIn Learning Course [Section 5 - Performance and Proceedures](https://www.linkedin.com/learning/cert-prep-faa-107-commercial-drone-license/what-does-the-test-cover?u=41282748)
    * Pilot's Handbook of Aero Knowledge: Ch 5, 5.33-5.43
    * Remote Pilot UAS Study Guide: Ch 4, pp 29-34



* UF LinkedIn Learning Course [Section 6 (ADM) - Section 7 (Maint. & Waivers)](https://www.linkedin.com/learning/cert-prep-faa-107-commercial-drone-license/what-does-the-test-cover?u=41282748)

* ADM  

    
    * Pilot's Handbook of Aero Knowledge: Ch 2, 2.1-2.32
    * Remote Pilot UAS Study Guide: Ch 10, pp 51-64
    
* Rules and Regs


  * TMacs Study Notes
  
  * 14 CFR Pt. 48  
    
    
    * 14 CFR Pt. 48.15
    * 14 CFR Pt. 48.20
    * 14 CFR Pt. 48.25
    * 14 CFR Pt. 48.100
    * 14 CFR Pt. 48.205
      
  * 14 CFR Pt. 107
    
## PRACTICE TESTS


  * Practice Tests and reviews
  
    

    
    



